(cl:defpackage universal_msgs-srv
  (:use )
  (:export
   "SENDHITBALLLOCATIONABS"
   "<SENDHITBALLLOCATIONABS-REQUEST>"
   "SENDHITBALLLOCATIONABS-REQUEST"
   "<SENDHITBALLLOCATIONABS-RESPONSE>"
   "SENDHITBALLLOCATIONABS-RESPONSE"
   "TRASH_LOCATION"
   "<TRASH_LOCATION-REQUEST>"
   "TRASH_LOCATION-REQUEST"
   "<TRASH_LOCATION-RESPONSE>"
   "TRASH_LOCATION-RESPONSE"
  ))

