// Generated by gencpp from file universal_msgs/Ball_Locations.msg
// DO NOT EDIT!


#ifndef UNIVERSAL_MSGS_MESSAGE_BALL_LOCATIONS_H
#define UNIVERSAL_MSGS_MESSAGE_BALL_LOCATIONS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace universal_msgs
{
template <class ContainerAllocator>
struct Ball_Locations_
{
  typedef Ball_Locations_<ContainerAllocator> Type;

  Ball_Locations_()
    : x()
    , y()
    , number()  {
    }
  Ball_Locations_(const ContainerAllocator& _alloc)
    : x(_alloc)
    , y(_alloc)
    , number(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _x_type;
  _x_type x;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _y_type;
  _y_type y;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _number_type;
  _number_type number;





  typedef boost::shared_ptr< ::universal_msgs::Ball_Locations_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::universal_msgs::Ball_Locations_<ContainerAllocator> const> ConstPtr;

}; // struct Ball_Locations_

typedef ::universal_msgs::Ball_Locations_<std::allocator<void> > Ball_Locations;

typedef boost::shared_ptr< ::universal_msgs::Ball_Locations > Ball_LocationsPtr;
typedef boost::shared_ptr< ::universal_msgs::Ball_Locations const> Ball_LocationsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::universal_msgs::Ball_Locations_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::universal_msgs::Ball_Locations_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace universal_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'universal_msgs': ['/home/robin/catkin_car/src/universal_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::universal_msgs::Ball_Locations_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::universal_msgs::Ball_Locations_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::universal_msgs::Ball_Locations_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::universal_msgs::Ball_Locations_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::universal_msgs::Ball_Locations_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::universal_msgs::Ball_Locations_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::universal_msgs::Ball_Locations_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dd76591bbd656c7519d60041cd4b0411";
  }

  static const char* value(const ::universal_msgs::Ball_Locations_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdd76591bbd656c75ULL;
  static const uint64_t static_value2 = 0x19d60041cd4b0411ULL;
};

template<class ContainerAllocator>
struct DataType< ::universal_msgs::Ball_Locations_<ContainerAllocator> >
{
  static const char* value()
  {
    return "universal_msgs/Ball_Locations";
  }

  static const char* value(const ::universal_msgs::Ball_Locations_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::universal_msgs::Ball_Locations_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32[] x\n\
int32[] y\n\
int32[] number\n\
";
  }

  static const char* value(const ::universal_msgs::Ball_Locations_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::universal_msgs::Ball_Locations_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.number);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Ball_Locations_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::universal_msgs::Ball_Locations_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::universal_msgs::Ball_Locations_<ContainerAllocator>& v)
  {
    s << indent << "x[]" << std::endl;
    for (size_t i = 0; i < v.x.size(); ++i)
    {
      s << indent << "  x[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.x[i]);
    }
    s << indent << "y[]" << std::endl;
    for (size_t i = 0; i < v.y.size(); ++i)
    {
      s << indent << "  y[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.y[i]);
    }
    s << indent << "number[]" << std::endl;
    for (size_t i = 0; i < v.number.size(); ++i)
    {
      s << indent << "  number[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.number[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // UNIVERSAL_MSGS_MESSAGE_BALL_LOCATIONS_H
