// Generated by gencpp from file universal_msgs/SendHitBallLocationABSRequest.msg
// DO NOT EDIT!


#ifndef UNIVERSAL_MSGS_MESSAGE_SENDHITBALLLOCATIONABSREQUEST_H
#define UNIVERSAL_MSGS_MESSAGE_SENDHITBALLLOCATIONABSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace universal_msgs
{
template <class ContainerAllocator>
struct SendHitBallLocationABSRequest_
{
  typedef SendHitBallLocationABSRequest_<ContainerAllocator> Type;

  SendHitBallLocationABSRequest_()
    : coord()  {
    }
  SendHitBallLocationABSRequest_(const ContainerAllocator& _alloc)
    : coord(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _coord_type;
  _coord_type coord;





  typedef boost::shared_ptr< ::universal_msgs::SendHitBallLocationABSRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::universal_msgs::SendHitBallLocationABSRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SendHitBallLocationABSRequest_

typedef ::universal_msgs::SendHitBallLocationABSRequest_<std::allocator<void> > SendHitBallLocationABSRequest;

typedef boost::shared_ptr< ::universal_msgs::SendHitBallLocationABSRequest > SendHitBallLocationABSRequestPtr;
typedef boost::shared_ptr< ::universal_msgs::SendHitBallLocationABSRequest const> SendHitBallLocationABSRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::universal_msgs::SendHitBallLocationABSRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::universal_msgs::SendHitBallLocationABSRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace universal_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'universal_msgs': ['/home/robin/catkin_car/src/universal_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::universal_msgs::SendHitBallLocationABSRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::universal_msgs::SendHitBallLocationABSRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::universal_msgs::SendHitBallLocationABSRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::universal_msgs::SendHitBallLocationABSRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::universal_msgs::SendHitBallLocationABSRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::universal_msgs::SendHitBallLocationABSRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::universal_msgs::SendHitBallLocationABSRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0a8680fa1e111dec9b1dbfc1af00ea9b";
  }

  static const char* value(const ::universal_msgs::SendHitBallLocationABSRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0a8680fa1e111decULL;
  static const uint64_t static_value2 = 0x9b1dbfc1af00ea9bULL;
};

template<class ContainerAllocator>
struct DataType< ::universal_msgs::SendHitBallLocationABSRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "universal_msgs/SendHitBallLocationABSRequest";
  }

  static const char* value(const ::universal_msgs::SendHitBallLocationABSRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::universal_msgs::SendHitBallLocationABSRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] coord\n\
";
  }

  static const char* value(const ::universal_msgs::SendHitBallLocationABSRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::universal_msgs::SendHitBallLocationABSRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.coord);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SendHitBallLocationABSRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::universal_msgs::SendHitBallLocationABSRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::universal_msgs::SendHitBallLocationABSRequest_<ContainerAllocator>& v)
  {
    s << indent << "coord[]" << std::endl;
    for (size_t i = 0; i < v.coord.size(); ++i)
    {
      s << indent << "  coord[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.coord[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // UNIVERSAL_MSGS_MESSAGE_SENDHITBALLLOCATIONABSREQUEST_H
