// Generated by gencpp from file universal_msgs/SendHitBallLocationABSResponse.msg
// DO NOT EDIT!


#ifndef UNIVERSAL_MSGS_MESSAGE_SENDHITBALLLOCATIONABSRESPONSE_H
#define UNIVERSAL_MSGS_MESSAGE_SENDHITBALLLOCATIONABSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace universal_msgs
{
template <class ContainerAllocator>
struct SendHitBallLocationABSResponse_
{
  typedef SendHitBallLocationABSResponse_<ContainerAllocator> Type;

  SendHitBallLocationABSResponse_()
    : success(false)  {
    }
  SendHitBallLocationABSResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::universal_msgs::SendHitBallLocationABSResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::universal_msgs::SendHitBallLocationABSResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SendHitBallLocationABSResponse_

typedef ::universal_msgs::SendHitBallLocationABSResponse_<std::allocator<void> > SendHitBallLocationABSResponse;

typedef boost::shared_ptr< ::universal_msgs::SendHitBallLocationABSResponse > SendHitBallLocationABSResponsePtr;
typedef boost::shared_ptr< ::universal_msgs::SendHitBallLocationABSResponse const> SendHitBallLocationABSResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::universal_msgs::SendHitBallLocationABSResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::universal_msgs::SendHitBallLocationABSResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace universal_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'universal_msgs': ['/home/robin/catkin_car/src/universal_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::universal_msgs::SendHitBallLocationABSResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::universal_msgs::SendHitBallLocationABSResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::universal_msgs::SendHitBallLocationABSResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::universal_msgs::SendHitBallLocationABSResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::universal_msgs::SendHitBallLocationABSResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::universal_msgs::SendHitBallLocationABSResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::universal_msgs::SendHitBallLocationABSResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::universal_msgs::SendHitBallLocationABSResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::universal_msgs::SendHitBallLocationABSResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "universal_msgs/SendHitBallLocationABSResponse";
  }

  static const char* value(const ::universal_msgs::SendHitBallLocationABSResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::universal_msgs::SendHitBallLocationABSResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n\
";
  }

  static const char* value(const ::universal_msgs::SendHitBallLocationABSResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::universal_msgs::SendHitBallLocationABSResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SendHitBallLocationABSResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::universal_msgs::SendHitBallLocationABSResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::universal_msgs::SendHitBallLocationABSResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UNIVERSAL_MSGS_MESSAGE_SENDHITBALLLOCATIONABSRESPONSE_H
