// Generated by gencpp from file universal_msgs/SendHitBallLocationABS.msg
// DO NOT EDIT!


#ifndef UNIVERSAL_MSGS_MESSAGE_SENDHITBALLLOCATIONABS_H
#define UNIVERSAL_MSGS_MESSAGE_SENDHITBALLLOCATIONABS_H

#include <ros/service_traits.h>


#include <universal_msgs/SendHitBallLocationABSRequest.h>
#include <universal_msgs/SendHitBallLocationABSResponse.h>


namespace universal_msgs
{

struct SendHitBallLocationABS
{

typedef SendHitBallLocationABSRequest Request;
typedef SendHitBallLocationABSResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SendHitBallLocationABS
} // namespace universal_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::universal_msgs::SendHitBallLocationABS > {
  static const char* value()
  {
    return "e50c9458a00924d9c4c833a9c3c086a0";
  }

  static const char* value(const ::universal_msgs::SendHitBallLocationABS&) { return value(); }
};

template<>
struct DataType< ::universal_msgs::SendHitBallLocationABS > {
  static const char* value()
  {
    return "universal_msgs/SendHitBallLocationABS";
  }

  static const char* value(const ::universal_msgs::SendHitBallLocationABS&) { return value(); }
};


// service_traits::MD5Sum< ::universal_msgs::SendHitBallLocationABSRequest> should match 
// service_traits::MD5Sum< ::universal_msgs::SendHitBallLocationABS > 
template<>
struct MD5Sum< ::universal_msgs::SendHitBallLocationABSRequest>
{
  static const char* value()
  {
    return MD5Sum< ::universal_msgs::SendHitBallLocationABS >::value();
  }
  static const char* value(const ::universal_msgs::SendHitBallLocationABSRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::universal_msgs::SendHitBallLocationABSRequest> should match 
// service_traits::DataType< ::universal_msgs::SendHitBallLocationABS > 
template<>
struct DataType< ::universal_msgs::SendHitBallLocationABSRequest>
{
  static const char* value()
  {
    return DataType< ::universal_msgs::SendHitBallLocationABS >::value();
  }
  static const char* value(const ::universal_msgs::SendHitBallLocationABSRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::universal_msgs::SendHitBallLocationABSResponse> should match 
// service_traits::MD5Sum< ::universal_msgs::SendHitBallLocationABS > 
template<>
struct MD5Sum< ::universal_msgs::SendHitBallLocationABSResponse>
{
  static const char* value()
  {
    return MD5Sum< ::universal_msgs::SendHitBallLocationABS >::value();
  }
  static const char* value(const ::universal_msgs::SendHitBallLocationABSResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::universal_msgs::SendHitBallLocationABSResponse> should match 
// service_traits::DataType< ::universal_msgs::SendHitBallLocationABS > 
template<>
struct DataType< ::universal_msgs::SendHitBallLocationABSResponse>
{
  static const char* value()
  {
    return DataType< ::universal_msgs::SendHitBallLocationABS >::value();
  }
  static const char* value(const ::universal_msgs::SendHitBallLocationABSResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UNIVERSAL_MSGS_MESSAGE_SENDHITBALLLOCATIONABS_H
