// Generated by gencpp from file universal_msgs/Trash_LocationRequest.msg
// DO NOT EDIT!


#ifndef UNIVERSAL_MSGS_MESSAGE_TRASH_LOCATIONREQUEST_H
#define UNIVERSAL_MSGS_MESSAGE_TRASH_LOCATIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace universal_msgs
{
template <class ContainerAllocator>
struct Trash_LocationRequest_
{
  typedef Trash_LocationRequest_<ContainerAllocator> Type;

  Trash_LocationRequest_()
    : x(0)
    , y(0)  {
    }
  Trash_LocationRequest_(const ContainerAllocator& _alloc)
    : x(0)
    , y(0)  {
  (void)_alloc;
    }



   typedef int32_t _x_type;
  _x_type x;

   typedef int32_t _y_type;
  _y_type y;





  typedef boost::shared_ptr< ::universal_msgs::Trash_LocationRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::universal_msgs::Trash_LocationRequest_<ContainerAllocator> const> ConstPtr;

}; // struct Trash_LocationRequest_

typedef ::universal_msgs::Trash_LocationRequest_<std::allocator<void> > Trash_LocationRequest;

typedef boost::shared_ptr< ::universal_msgs::Trash_LocationRequest > Trash_LocationRequestPtr;
typedef boost::shared_ptr< ::universal_msgs::Trash_LocationRequest const> Trash_LocationRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::universal_msgs::Trash_LocationRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::universal_msgs::Trash_LocationRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace universal_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'universal_msgs': ['/home/robin/catkin_car/src/universal_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::universal_msgs::Trash_LocationRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::universal_msgs::Trash_LocationRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::universal_msgs::Trash_LocationRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::universal_msgs::Trash_LocationRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::universal_msgs::Trash_LocationRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::universal_msgs::Trash_LocationRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::universal_msgs::Trash_LocationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bd7b43fd41d4c47bf5c703cc7d016709";
  }

  static const char* value(const ::universal_msgs::Trash_LocationRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbd7b43fd41d4c47bULL;
  static const uint64_t static_value2 = 0xf5c703cc7d016709ULL;
};

template<class ContainerAllocator>
struct DataType< ::universal_msgs::Trash_LocationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "universal_msgs/Trash_LocationRequest";
  }

  static const char* value(const ::universal_msgs::Trash_LocationRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::universal_msgs::Trash_LocationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 x\n\
int32 y\n\
";
  }

  static const char* value(const ::universal_msgs::Trash_LocationRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::universal_msgs::Trash_LocationRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Trash_LocationRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::universal_msgs::Trash_LocationRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::universal_msgs::Trash_LocationRequest_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int32_t>::stream(s, indent + "  ", v.y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UNIVERSAL_MSGS_MESSAGE_TRASH_LOCATIONREQUEST_H
