// Generated by gencpp from file universal_msgs/Trash_Location.msg
// DO NOT EDIT!


#ifndef UNIVERSAL_MSGS_MESSAGE_TRASH_LOCATION_H
#define UNIVERSAL_MSGS_MESSAGE_TRASH_LOCATION_H

#include <ros/service_traits.h>


#include <universal_msgs/Trash_LocationRequest.h>
#include <universal_msgs/Trash_LocationResponse.h>


namespace universal_msgs
{

struct Trash_Location
{

typedef Trash_LocationRequest Request;
typedef Trash_LocationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Trash_Location
} // namespace universal_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::universal_msgs::Trash_Location > {
  static const char* value()
  {
    return "297290d6ee8d47376b41d0866bb23c06";
  }

  static const char* value(const ::universal_msgs::Trash_Location&) { return value(); }
};

template<>
struct DataType< ::universal_msgs::Trash_Location > {
  static const char* value()
  {
    return "universal_msgs/Trash_Location";
  }

  static const char* value(const ::universal_msgs::Trash_Location&) { return value(); }
};


// service_traits::MD5Sum< ::universal_msgs::Trash_LocationRequest> should match 
// service_traits::MD5Sum< ::universal_msgs::Trash_Location > 
template<>
struct MD5Sum< ::universal_msgs::Trash_LocationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::universal_msgs::Trash_Location >::value();
  }
  static const char* value(const ::universal_msgs::Trash_LocationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::universal_msgs::Trash_LocationRequest> should match 
// service_traits::DataType< ::universal_msgs::Trash_Location > 
template<>
struct DataType< ::universal_msgs::Trash_LocationRequest>
{
  static const char* value()
  {
    return DataType< ::universal_msgs::Trash_Location >::value();
  }
  static const char* value(const ::universal_msgs::Trash_LocationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::universal_msgs::Trash_LocationResponse> should match 
// service_traits::MD5Sum< ::universal_msgs::Trash_Location > 
template<>
struct MD5Sum< ::universal_msgs::Trash_LocationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::universal_msgs::Trash_Location >::value();
  }
  static const char* value(const ::universal_msgs::Trash_LocationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::universal_msgs::Trash_LocationResponse> should match 
// service_traits::DataType< ::universal_msgs::Trash_Location > 
template<>
struct DataType< ::universal_msgs::Trash_LocationResponse>
{
  static const char* value()
  {
    return DataType< ::universal_msgs::Trash_Location >::value();
  }
  static const char* value(const ::universal_msgs::Trash_LocationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UNIVERSAL_MSGS_MESSAGE_TRASH_LOCATION_H
